import logging
import os
import pyttsx3
import speech_recognition as sr
import datetime
import wikipedia
import webbrowser
import google.generativeai as genai
import pyautogui

from pycaw.pycaw import AudioUtilities, IAudioEndpointVolume
from comtypes import CLSCTX_ALL
from ctypes import POINTER, cast
import time

import screen_brightness_control as sbc

# Logging Configuration

LOG_DIR = "logs"
os.makedirs(LOG_DIR, exist_ok=True)

LOG_FILE_NAME = "application.log"
log_path = os.path.join(LOG_DIR, LOG_FILE_NAME)

logging.basicConfig(
    filename=log_path,
    format="[ %(asctime)s ] %(name)s - %(levelname)s - %(message)s",
    level=logging.INFO,
)

# Activating voice from our system

engine = pyttsx3.init("sapi5")

voices = engine.getProperty("voices")
engine.setProperty("voice", voices[0].id)  

rate = engine.getProperty("rate")
engine.setProperty("rate", 170)  


def speak(text):
    """
    Converts the given text to speech and plays it through the system's speakers.

    Args:
        text (str): The text to convert to speech.

    Returns:
        None
    """
    engine.say(text)
    engine.runAndWait()


def take_command():
    """
    Listens to microphone input, recognizes speech using Google API, and converts it to text.

    Returns:
        str: The recognized speech as text. Returns "None" if recognition fails.
    """
    r = sr.Recognizer()
    with sr.Microphone() as source:
        print("Adjusting for ambient noise, please wait...")
        r.adjust_for_ambient_noise(source, duration=1)

        print("Listening...")
        try:
            audio = r.listen(source)
            print("Recognizing...")
            query = r.recognize_google(audio, language="en-in")
            print(f"You said: {query}")
        except Exception as e:
            logging.info(e)
            print("Say that again please.")
            return "None"

        return query


def greeting():
    """
    Greets the user based on the current time of day.

    Returns:
        None
    """
    hour = datetime.datetime.now().hour
    if hour >= 0 and hour <= 12:
        speak("Good morning Sir. How can I help you?")
    elif hour > 12 and hour <= 18:
        speak("Good afternoon Sir. How can I help you?")
    else:
        speak("Good night Sir. How can I help you?")


def wikipedia_search(query):
    """
    Searches Wikipedia for the provided query and reads the first 2 sentences.

    Args:
        query (str): The topic to search on Wikipedia.

    Returns:
        None
    """
    try:
        topic = query.replace("wikipedia", "").strip()
        logging.info(f"Searching Wikipedia for: {topic}")
        result = wikipedia.summary(topic, sentences=2)
        speak(result)
    except Exception as e:
        speak("Something went wrong while fetching information.")
        logging.error(f"Wikipedia Error: {e}")


def open_website(name, url):
    """
    Opens a website in the default browser and announces the action.

    Args:
        name (str): The name of the website (for voice feedback).
        url (str): The URL of the website to open.

    Returns:
        None
    """
    speak(f"Ok I'm Opening {name}...")
    logging.info(f"Opening website: {name} -> {url}")
    webbrowser.open(url)


def gemini_model_response(user_input):
    """
    Generates a short response using the Gemini API for the provided user input.

    Args:
        user_input (str): The user's question or statement.

    Returns:
        str: The text response generated by the Gemini API.
    """
    GEMINI_API_KEY = "AIzaSyAuhJ7OkBSnL9XHBFZa2pS04ZN8uAo20v4"
    genai.configure(api_key=GEMINI_API_KEY)
    model = genai.GenerativeModel("gemini-2.5-flash")
    prompt = f"You are Jarvis, act as Jarvis a voice assistant for sadat. Answer the provided question too shortly in 1 or 2 line. the question is {user_input}"
    res = model.generate_content(prompt)
    logging.info("User asked to gemini.")
    return res.text


# ======================= Window Commands =========================

def close_active_window():
    """
    Closes the currently active window.

    Returns:
        None
    """
    pyautogui.hotkey("alt", "f4")
    speak("Closed the active window.")
    logging.info("Closed active window")


def minimize_window():
    """
    Minimizes the currently active window.

    Returns:
        None
    """
    pyautogui.hotkey("win", "down")
    speak("Window minimized.")
    logging.info("Minimized window")


def maximize_window():
    """
    Maximizes the currently active window.

    Returns:
        None
    """
    pyautogui.hotkey("win", "up")
    speak("Window maximized.")
    logging.info("Maximized window")


def restore_window():
    """
    Restores the currently active window from minimized state.

    Returns:
        None
    """
    pyautogui.hotkey("win", "down")
    speak("Window restored.")
    logging.info("Restored window")


def switch_window():
    """
    Switches to the next open window.

    Returns:
        None
    """
    pyautogui.hotkey("alt", "tab")
    speak("Switched window.")
    logging.info("Switched window")


# ========================= System Settings ==========================

def volume_up():
    """
    Increases system volume by 5 steps using simulated key presses.

    Returns:
        None
    """
    try:
        for _ in range(5):
            pyautogui.press('volumeup')
            time.sleep(0.1)
        speak("Volume increased by 5 steps")
        logging.info("Volume increased by 5 percent")
    except Exception as e:
        speak("Could not increase volume")
        logging.error(f"Volume Up Error: {e}")


def volume_down():
    """
    Decreases system volume by 5 steps using simulated key presses.

    Returns:
        None
    """
    try:
        for _ in range(5):
            pyautogui.press('volumedown')
            time.sleep(0.1)
        speak("Volume decreased by 5 steps")
        logging.info("Volume decreased by 5 percent")
    except Exception as e:
        speak("Could not decrease volume")
        logging.error(f"Volume Down Error: {e}")


def mute_volume():
    """
    Mutes the system volume.

    Returns:
        None
    """
    try:
        pyautogui.press('volumemute')
        speak("Volume muted")
        logging.info("Volume muted")
    except Exception as e:
        speak("Could not mute volume")
        logging.error(f"Mute Error: {e}")


def brightness_up():
    """
    Increases the screen brightness by 10% (up to 100%).

    Returns:
        None
    """
    try:
        current = sbc.get_brightness(display=0)[0]
        new = min(current + 10, 100)
        sbc.set_brightness(new)
        speak(f"Brightness increased to {new}%")
        logging.info(f"Brightness increased to {new}%")
    except Exception as e:
        speak("Could not increase brightness")
        logging.error(f"Brightness Up Error: {e}")


def brightness_down():
    """
    Decreases the screen brightness by 10% (down to 0%).

    Returns:
        None
    """
    try:
        current = sbc.get_brightness(display=0)[0]
        new = max(current - 10, 0)
        sbc.set_brightness(new)
        speak(f"Brightness decreased to {new}%")
        logging.info(f"Brightness decreased to {new}%")
    except Exception as e:
        speak("Could not decrease brightness")
        logging.error(f"Brightness Down Error: {e}")


def scroll_up():
    """
    Scrolls the current window or page upwards.

    Returns:
        None
    """
    try:
        pyautogui.scroll(800)
        logging.info("Scrolled up")
    except Exception as e:
        speak("Could not scroll up")
        logging.error(f"Scroll Up Error: {e}")


def scroll_down():
    """
    Scrolls the current window or page downwards.

    Returns:
        None
    """
    try:
        pyautogui.scroll(-800)
        logging.info("Scrolled down")
    except Exception as e:
        speak("Could not scroll down")
        logging.error(f"Scroll Down Error: {e}")




greeting()

while True:
    query = take_command().lower().strip()
    print(query)

    if "your name" in query or "who are you" in query:
        speak("I'm Jarvis, at your service. Made by sir, Sadat the handsome.")
        logging.info("User asked for assistant's name.")

    elif "time" in query:
        strTime = datetime.datetime.now().strftime("%H:%M:%S")
        speak(f"Sir the time is {strTime}")
        logging.info("User asked for current time.")

    elif "stop" in query or "exit" in query or "quit" in query:
        speak("Goodbye Sir. Have a nice day.")
        break

    elif "wikipedia" in query:
        speak("Searching Wikipedia...")
        wikipedia_search(query)
        
    elif "open" in query and "youtube" in query:
        open_website("YouTube", "https://www.youtube.com")

    elif "open" in query and "google" in query:
        open_website("Google", "https://www.google.com")

    elif "open" in query and "linkedin" in query:
        open_website("Linkedin", "https://www.linkedin.com/in/muhaiminul-sadat-4a574736b/")
    
    elif 'open' in query and 'facebook' in query:
        open_website('facebook','facebook.com')

    elif "close" in query:
        close_active_window()

    elif "minimize" in query or 'minimise' in query:
        minimize_window()

    elif "maximize" in query or "full screen" in query or "fullscreen" in query:
        print("Maximize block fired")
        maximize_window()

    elif "restore window" in query:
        restore_window()

    elif "switch window" in query:
        switch_window()

    elif "volume" in query and ("increase" in query or 'up' in query):
        volume_up()
    
    elif "volume" in query and ('down' in query or 'decrease' in query) :
        volume_down()
    
    elif "volume" in query and 'mute' in query :
        mute_volume()
    
    elif "brightness" in query and ('down' in query or 'decrease' in query) :
        brightness_down()
    
    elif "brightness" in query and ('up' in query or 'increase' in query) :
        brightness_up()

    elif 'up' in query:
        scroll_up()

    elif 'down' in query:
        scroll_down()
    

    else:
        res = gemini_model_response(query)
        speak(res)
